// src/views/TaskBoardView.vue
<template>
  <div>
    <div class="flex bg-slate-100 border-2 border-slate-400">
      <span class="flex-1">Trello Board</span>
      <button type="button" class="flex ml-auto" @click="addLane">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-6 w-6 text-green-400"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="2"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M12 4v16m8-8H4"
          />
        </svg>
        <span>Add Lane</span>
      </button>
    </div>
    <div class="">
      <div class="v-screen flex overflow-scroll">
        <div
          v-for="lane in laneStore.sortedLanes"
          :key="lane._id"
          class="lane border-2 rounded-md min-w-250"
        >
          <editable-label
            :label="lane.name"
            @updateLabel="(label:string) => saveLane(lane, label)"
          ></editable-label>
          <div class="flex flex-row justify-end">
            <button @click="addTask(lane)">Add Task</button>
          </div>
          <task-card :task="task"></task-card>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { LoremIpsum } from 'lorem-ipsum';
import type { Lane, Task } from 'stores/db';
import { useLaneStore } from 'stores/lane';
import { onMounted } from 'vue';
import EditableLabel from 'components/EditableLabel.vue';
import TaskCard from 'components/TaskCard.vue';

const lorem = new LoremIpsum();

const sentence = () => lorem.generateSentences(2);
const range = (max: number) => Math.floor(Math.random() * max + 3);
const laneStore = useLaneStore();

const task: Task = {
  _id: 'testTask',
  name: 'Task',
  description: sentence(),
  category: 'Default',
  lane: 'Lane',
  createdAt: new Date(),
  updatedAt: new Date(),
};

onMounted(async () => {
  await laneStore.fetchLanes();
});

const addLane = async () => {
  const newLane: Lane = laneStore.newLane('');
  const savedLane = await laneStore.saveLane(newLane);
};

const saveLane = async (lane: Lane, name: string) => {
  lane.name = name;
  await laneStore.saveLane(lane);
};

const addTask = async (lane: Lane) => {
  console.log('addTask to lane ', lane.name);
};
</script>

<style scoped>
.lane {
  min-width: 250px;
  max-width: 250px;
}

.card {
  margin-bottom: 10px;
}

.card-body {
  border-top: 2px solid darkgray;
}

.bd-highlight {
  border: 1px solid gray;
  background-color: lightcyan;
}
</style>

// src/views/TaskBoardView.tsx
import {LoremIpsum} from 'lorem-ipsum';
import laneStore, {newLane} from '@/stores/lane'
import '@/views/TaskBoardView.scss'
import {Lane, Task} from "@/stores/db";
import task from "@/stores/task";
import React from 'react';

const lorem = new LoremIpsum();

const sentence = (): string => lorem.generateSentences(2);

function TaskBoardView() {
  let thisTask: Task = {
    _id: 'first',
    name: 'First Task',
    lane: 'Todos',
    category: 'First',
    description: sentence(),
    createdAt: new Date(),
    updatedAt: new Date()
  }

  const Card = (task: Task) => (
    <div className="card" key={task._id}>
      <div>{task.category}</div>
      <div className="card-body">
        <div className="card-title">{task.name}</div>
        <div className="card-text">
          {task.description}
        </div>
      </div>
    </div>)

  const Cards = () => {
    return (
      <React.Fragment>
        {[thisTask].map((task: Task) => Card(task))}
      </React.Fragment>
    );
  }

  const Lane = (lane: Lane) => (
    <div key={lane._id} className="p-2 lane">
      <div className="lane-title">{lane.name}</div>
      <Cards></Cards>
    </div>
  )
  const Lanes = () => (
    <React.Fragment>
      {laneStore.sortedLanes.map((lane: Lane) => Lane(lane))}
    </React.Fragment>
  )

  const AddLaneButton = () => {
    return (
      <div className={"flex-shrink-1 add-lane-tooltip-wrapper"}>
        <svg
          onClick={addLane}
          xmlns="http://www.w3.org/2000/svg"
          className="lane-button-icon"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          strokeWidth="4"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M12 4v16m8-8H4"
          />
        </svg>
        <div className={"add-lane-tooltip"}>
          Add Lane
        </div>
      </div>
    )
  }

  const addLane = () => {
    laneStore.saveLane(newLane())
  }

  return (
    <div className={"container-fluid"}>
      <div className={"header d-flex"}>
        <div className={"col flex-grow-1"}>Trello Board</div>
        <AddLaneButton></AddLaneButton>
      </div>
      <div className="row">
        <div className="cardwall d-flex overflow-scroll">
          <Lanes></Lanes>
        </div>
      </div>
    </div>
  )
}

export default TaskBoardView
